version: '{build}'
image: Visual Studio 2019
install:
  - ps: '& .\prebuild.ps1'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
nuget:
  disable_publish_on_pr: true
before_build:
- ps: dotnet restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
test: off
artifacts:
- path: '**\*.nupkg'
  name: NuGet Packages
- path: '**\*.snupkg'
  name: NuGet Symbols Packages
deploy:
- provider: NuGet
  server: https://www.myget.org/F/nulldesk-ci/api/v2/package
  api_key:
    secure: uBiyeuaz9rRv16bZe/X6HID91rZK//umRAHXo0gRh8l57p8MElDVETuqSwFXZVme
  symbol_server: https://www.myget.org/F/nulldesk-ci/symbols/api/v2/package
  on:
    branch: master
- provider: NuGet
  name: production
  api_key:
    secure: QAxZSIPDkPX/ziDi/D7MZ4nF3bimBfEQ35RiKwO0Lug7HE3lvqGC/zAs1HrWfrDY
  on:
    branch: master
    appveyor_repo_tag: true
# Build Notes
# To manually push nupkg and snupkg files (if appveyor is only able to upload legacy versions with non-portable PDB files and legacy symbols)
#    build locally with build.ps1 on SDK 2.2.200 or later (remember to set the env variable for the tag if you want release version)
#    run nuget push manually:
#      dotnet nuget push .\dist\*.* -s https://api.nuget.org/v3/index.json -k <key here>
# To download an SDK, edit the install section -- get paths for SDK binaries from release notes here: https://github.com/dotnet/core/tree/master/release-notes