version: '{build}'  
install:  
  - ps: '& .\prebuild.ps1'
  # Download install script to install .NET cli in .dotnet dir
  - ps: mkdir -Force ".\scripts\obtain\" | Out-Null
  - ps: Invoke-WebRequest "https://raw.githubusercontent.com/dotnet/cli/v1.0.0-rc4-004771/scripts/obtain/dotnet-install.ps1" -OutFile ".\scripts\obtain\install.ps1"
  - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetcli"
  - ps: '& .\scripts\obtain\install.ps1'
  # add dotnet to PATH
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"
pull_requests:  
  do_not_increment_build_number: true
branches:  
  only:
  - master
nuget:  
  disable_publish_on_pr: true
build_script:  
- ps: .\build.ps1
test: off  
artifacts:  
- path: .\dist\**\*.nupkg
  name: NuGet
deploy:  
- provider: NuGet
  server: https://www.myget.org/F/nulldesk-ci/api/v2/package
  api_key:
    secure: uBiyeuaz9rRv16bZe/X6HID91rZK//umRAHXo0gRh8l57p8MElDVETuqSwFXZVme
  symbol_server: https://www.myget.org/F/nulldesk-ci/symbols/api/v2/package
  on:
    branch: master
- provider: NuGet
  name: production
  api_key:
    secure: SVm9O7Z3pB1N1lIPerJOc1MMMRiadRtmueLyIGkik192ID/Ip6enpjNr64tek+Xj
  on:
    branch: master
    appveyor_repo_tag: true